### ISSUE TITLE
Please share an updated fully working pre-built IMG for PiZero H2+

### ISSUE THREAD

**Issue by a0a0max** [robertojguerra/orangepi-zero-full-setup#1]
Hello,

Thank you very much for the manual,

however, could you please share an updated fully working server IMG for Orange Pi Zero H2+?

Last available build fully working with TV OUT is dated 2018 :(

It would be very appreciated. 

Best regards,
Jamiro

**Comment by Giovmor78** [comment]
+1
Just signed in for the same request.

Need an update image ready to flash

Thank you man.

**Comment by robertojguerra** [comment]
This patch was included in the armbian project already :)

Use the latest Armbian for orange pi zero, and make sure that /boot/armbianEnv.txt has "overlays=... ... tve" (TV encoder)

Then verify that you have /dev/fb0

apt install lightdm
reboot
